# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Jacek''s C++ Blog'
tagline:          'An Engineer''s Coder Blog'
description:      'Writing about daily experiences and thoughts with C++ as my main work language.'
url:              http://blog.galowicz.de
baseurl:          /

author:
  name:           'Jacek Galowicz'
  url:            http://galowicz.de

twitter_username:     jgalowicz
github_username:      tfc
linkedin_username:    jgalowicz
google_plus_username: +JacekGalowicz
xing_username:        Jacek_Galowicz

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:             [jekyll-paginate, jekyll-gist]
